version: '3'

services:
  convert:
    image: pluswerk/convert-svg-to-png
    container_name: convert
    ports:
      - 8999:3000
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /usr/src/app
    container_name: "dev"
    volumes:
      - "./:/usr/src/app"
      - /usr/src/app/node_modules
    ports:
      - "3300:3300"
    depends_on:
      - convert
    command: npm start
